// Master Weapon Database Array (75 Weapons Mapped)
const weaponDatabase = [
  // --- ARTS UNITS ---
  { name: "Oblivion", category: "Arts Units", secondaryStat: "Arts DMG Boost", skillStat: "Twilight" },
  { name: "Resonant Echo", category: "Arts Units", secondaryStat: "Arts Intensity Boost", skillStat: "Infliction" },
  { name: "Astral Compass", category: "Arts Units", secondaryStat: "Arts DMG Boost", skillStat: "Efficacy" },
  { name: "Prismatic Core", category: "Arts Units", secondaryStat: "Critical Rate Boost", skillStat: "Combative" },
  { name: "Pulse Transmitter", category: "Arts Units", secondaryStat: "Electric DMG Boost", skillStat: "Detonate" },
  { name: "Frostbite Conduit", category: "Arts Units", secondaryStat: "Cryo DMG Boost", skillStat: "Suppression" },
  { name: "Thermal Amplifier", category: "Arts Units", secondaryStat: "Heat DMG Boost", skillStat: "Fracture" },
  { name: "Verdant Prism", category: "Arts Units", secondaryStat: "Nature DMG Boost", skillStat: "Inspiring" },
  { name: "Chrono Relay", category: "Arts Units", secondaryStat: "Ultimate Gain Efficiency Boost", skillStat: "Flow" },
  { name: "Lifesovereign Staff", category: "Arts Units", secondaryStat: "Treatment Efficiency Boost", skillStat: "Medicant" },
  { name: "Aetherial Focus", category: "Arts Units", secondaryStat: "Attack Boost", skillStat: "Assault" },
  { name: "Aegis Weaver", category: "Arts Units", secondaryStat: "HP Boost", skillStat: "Brutality" },
  { name: "Cataclysm Emitter", category: "Arts Units", secondaryStat: "Arts DMG Boost", skillStat: "Crusher" },
  { name: "Null-Zone Catalyst", category: "Arts Units", secondaryStat: "Arts Intensity Boost", skillStat: "Pursuit" },
  { name: "Singularity Iris", category: "Arts Units", secondaryStat: "Critical Rate Boost", skillStat: "Twilight" },

  // --- GREATSWORDS ---
  { name: "Eminent Repute", category: "Greatswords", secondaryStat: "Physical DMG Boost", skillStat: "Twilight" },
  { name: "Titan's Cleaver", category: "Greatswords", secondaryStat: "Attack Boost", skillStat: "Crusher" },
  { name: "Ironclad Slicer", category: "Greatswords", secondaryStat: "HP Boost", skillStat: "Brutality" },
  { name: "Infernal Blade", category: "Greatswords", secondaryStat: "Heat DMG Boost", skillStat: "Detonate" },
  { name: "Glacial Edge", category: "Greatswords", secondaryStat: "Cryo DMG Boost", skillStat: "Fracture" },
  { name: "Storm Splitter", category: "Greatswords", secondaryStat: "Electric DMG Boost", skillStat: "Assault" },
  { name: "Gaia's Might", category: "Greatswords", secondaryStat: "Nature DMG Boost", skillStat: "Combative" },
  { name: "Ruins Breaker", category: "Greatswords", secondaryStat: "Physical DMG Boost", skillStat: "Suppression" },
  { name: "Sovereign Greatsword", category: "Greatswords", secondaryStat: "Critical Rate Boost", skillStat: "Pursuit" },
  { name: "Bloodline Claymore", category: "Greatswords", secondaryStat: "HP Boost", skillStat: "Medicant" },
  { name: "Abyssal Sever", category: "Greatswords", secondaryStat: "Arts DMG Boost", skillStat: "Infliction" },
  { name: "Vanguard Bastion", category: "Greatswords", secondaryStat: "Attack Boost", skillStat: "Inspiring" },
  { name: "Executioner's Toll", category: "Greatswords", secondaryStat: "Critical Rate Boost", skillStat: "Crusher" },
  { name: "Dominion Sword", category: "Greatswords", secondaryStat: "Ultimate Gain Efficiency Boost", skillStat: "Flow" },
  { name: "Zero Impact", category: "Greatswords", secondaryStat: "Arts Intensity Boost", skillStat: "Efficacy" },

  // --- SWORDS ---
  { name: "Blessing of Lustrous Carmine", category: "Swords", secondaryStat: "Heat DMG Boost", skillStat: "Flow" },
  { name: "Swiftwing Rapier", category: "Swords", secondaryStat: "Critical Rate Boost", skillStat: "Pursuit" },
  { name: "Vanguard Saber", category: "Swords", secondaryStat: "Attack Boost", skillStat: "Assault" },
  { name: "Frost Fang", category: "Swords", secondaryStat: "Cryo DMG Boost", skillStat: "Suppression" },
  { name: "Thunderflash Blade", category: "Swords", secondaryStat: "Electric DMG Boost", skillStat: "Detonate" },
  { name: "Verdant Scimitar", category: "Swords", secondaryStat: "Nature DMG Boost", skillStat: "Inspiring" },
  { name: "Iron Sentinel", category: "Swords", secondaryStat: "HP Boost", skillStat: "Medicant" },
  { name: "Arcane Needle", category: "Swords", secondaryStat: "Arts DMG Boost", skillStat: "Twilight" },
  { name: "Null-Edge", category: "Swords", secondaryStat: "Arts Intensity Boost", skillStat: "Infliction" },
  { name: "Radiant Estoc", category: "Swords", secondaryStat: "Ultimate Gain Efficiency Boost", skillStat: "Efficacy" },
  { name: "Shatterglass Blade", category: "Swords", secondaryStat: "Physical DMG Boost", skillStat: "Fracture" },
  { name: "Honor Guard Sword", category: "Swords", secondaryStat: "Treatment Efficiency Boost", skillStat: "Combative" },
  { name: "Eclipse Longsword", category: "Swords", secondaryStat: "Critical Rate Boost", skillStat: "Brutality" },
  { name: "Tempest Katana", category: "Swords", secondaryStat: "Attack Boost", skillStat: "Crusher" },
  { name: "Phantom Grace", category: "Swords", secondaryStat: "Physical DMG Boost", skillStat: "Flow" },

  // --- HANDCANNONS ---
  { name: "Foundational Code", category: "Handcannons", secondaryStat: "Electric DMG Boost", skillStat: "Efficacy" },
  { name: "Wildfire Revolver", category: "Handcannons", secondaryStat: "Heat DMG Boost", skillStat: "Detonate" },
  { name: "Precision Deadeye", category: "Handcannons", secondaryStat: "Critical Rate Boost", skillStat: "Pursuit" },
  { name: "Heavy Magnum", category: "Handcannons", secondaryStat: "Physical DMG Boost", skillStat: "Crusher" },
  { name: "Cryo Sidearm", category: "Handcannons", secondaryStat: "Cryo DMG Boost", skillStat: "Suppression" },
  { name: "Bio-Hazard Pistol", category: "Handcannons", secondaryStat: "Nature DMG Boost", skillStat: "Infliction" },
  { name: "Overclock Blaster", category: "Handcannons", secondaryStat: "Ultimate Gain Efficiency Boost", skillStat: "Flow" },
  { name: "Aegis Defender Pistol", category: "Handcannons", secondaryStat: "HP Boost", skillStat: "Brutality" },
  { name: "Arc Pulse Handcannon", category: "Handcannons", secondaryStat: "Arts DMG Boost", skillStat: "Twilight" },
  { name: "Enforcer 9mm", category: "Handcannons", secondaryStat: "Attack Boost", skillStat: "Assault" },
  { name: "Signal Flare", category: "Handcannons", secondaryStat: "Arts Intensity Boost", skillStat: "Inspiring" },
  { name: "Lifeline Injector Pistol", category: "Handcannons", secondaryStat: "Treatment Efficiency Boost", skillStat: "Medicant" },
  { name: "Fracture Cannon", category: "Handcannons", secondaryStat: "Physical DMG Boost", skillStat: "Fracture" },
  { name: "Apex Marksman", category: "Handcannons", secondaryStat: "Critical Rate Boost", skillStat: "Combative" },
  { name: "Void Trigger", category: "Handcannons", secondaryStat: "Arts DMG Boost", skillStat: "Efficacy" },

  // --- POLEARMS ---
  { name: "Wilderness Echo", category: "Polearms", secondaryStat: "Critical Rate Boost", skillStat: "Pursuit" },
  { name: "Vanguard Lance", category: "Polearms", secondaryStat: "Attack Boost", skillStat: "Assault" },
  { name: "Dragon-Spine Spear", category: "Polearms", secondaryStat: "Physical DMG Boost", skillStat: "Brutality" },
  { name: "Inferno Halberd", category: "Polearms", secondaryStat: "Heat DMG Boost", skillStat: "Detonate" },
  { name: "Glacial Trident", category: "Polearms", secondaryStat: "Cryo DMG Boost", skillStat: "Suppression" },
  { name: "Storm-Caller Spear", category: "Polearms", secondaryStat: "Electric DMG Boost", skillStat: "Flow" },
  { name: "Verdant Partisan", category: "Polearms", secondaryStat: "Nature DMG Boost", skillStat: "Inspiring" },
  { name: "Iron Glaive", category: "Polearms", secondaryStat: "HP Boost", skillStat: "Combative" },
  { name: "Arcane Naginata", category: "Polearms", secondaryStat: "Arts DMG Boost", skillStat: "Twilight" },
  { name: "Null-Point Lance", category: "Polearms", secondaryStat: "Arts Intensity Boost", skillStat: "Infliction" },
  { name: "Sovereign Pike", category: "Polearms", secondaryStat: "Ultimate Gain Efficiency Boost", skillStat: "Crusher" },
  { name: "Medic Halberd", category: "Polearms", secondaryStat: "Treatment Efficiency Boost", skillStat: "Medicant" },
  { name: "Armor-Piercer Spear", category: "Polearms", secondaryStat: "Physical DMG Boost", skillStat: "Fracture" },
  { name: "Celestial Reach", category: "Polearms", secondaryStat: "Critical Rate Boost", skillStat: "Efficacy" },
  { name: "Titan's Pillar", category: "Polearms", secondaryStat: "HP Boost", skillStat: "Brutality" }
];